name: Docker Image CI

on:
  schedule:
    - cron:  '13 * * * *'
  workflow_dispatch: ~

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag deluged:$(date +%s)
