name: Docker Image CI

on:
  schedule:
    - cron:  '13 * * * *'
  workflow_dispatch: ~

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
      run: |
        ./check-build-push.sh
